---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgC8eRIADH+2YPOYTjEx98yqeGr/EfmQGj7qqehGbliCwEqRxAcodwG3i12Ts5yjvbmsiQTTf2nSK2vm+mqCVkWALJ8OycRA+O2bLs/dibGNNk5BuQOymoRh+qgBTaZa/CaIhxtJWIn86Y9q13CiidIkJx1dEr++UB0ubUBEH3rc9dYU407uNkDH4hVH93JiMTDroU9Jm+XI+kl8y8ndY9opus5rVeYJHM3FF3ypRTdrzaF+3uCuoIkFWhxRTv9ib42hST3q46H7zM1SRyOAZEnoOLhyQWc+zH3azIB/CRZd8rmfI8uue7G+hJ3rOcV9Qv/+1FoL/GXxSiFKCTddyl0POUC7u1K2VBHofdV1bNyL4HGgBM7W+JLphmPSzfkygiPHkSXwIBEavSWzDHmE5uh2Tq3cmRjAcl+Hm5Ag+7uAGo7CJ85U6INe4/x7I2Fyv7xUYsiBZCeheDJUCEu//oWMMD0TKB0+SXiQcAwKRRR5gA1bMW9Ir3Y8t0XAW/XolCuYeGxtTw5rej9vRR/k+Mdu1F7U6kcOjTSQnRdL/fUJepLO8atZvpJGiZ0vEtaehUEOzkU8VJYOSHk2jj/o0OsowQ0bGqFX6Nrov2SEAoNjMB80qUPju+T1HAQkLwWwhaRvZj7D36CZZ+xtIY4GvbLIoDXQATMCpkKcDH3mEMAwkybmYSCBvgfkgqF9n5wR17ri257ywdedS0R324NhkqiaW5cuTnQqU3pl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database
